version: '3'

services:
  postgis:
    image: mdillon/postgis
    volumes:
      - volumes-city-search-postgis:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=city_search_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - city_search

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgis
    networks:
      - city_search

volumes:
  "volumes-city-search-postgis":

networks:
  city_search:
